import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { listPlans, listProjects, updatePlanStatus } from '../api/client'
import type { Plan, Project } from '../types'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

const STATUS_STYLES: Record<string, { label: string; color: string; bg: string }> = {
  pending:   { label: 'Pending',   color: 'text-yellow-400', bg: 'bg-yellow-900/20 border-yellow-700/40' },
  accepted:  { label: 'Accepted',  color: 'text-emerald-400', bg: 'bg-emerald-900/20 border-emerald-700/40' },
  rejected:  { label: 'Rejected',  color: 'text-orange-400', bg: 'bg-orange-900/20 border-orange-700/40' },
  completed: { label: 'Completed', color: 'text-blue-400', bg: 'bg-blue-900/20 border-blue-700/40' },
  abandoned: { label: 'Abandoned', color: 'text-gray-400', bg: 'bg-gray-800/40 border-gray-700/40' },
}

function formatTime(iso: string): string {
  const d = new Date(iso)
  const now = new Date()
  const diffMs = now.getTime() - d.getTime()
  const diffMin = Math.floor(diffMs / 60000)
  if (diffMin < 1) return 'just now'
  if (diffMin < 60) return `${diffMin}m ago`
  const diffHrs = Math.floor(diffMin / 60)
  if (diffHrs < 24) return `${diffHrs}h ago`
  return d.toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
}

export default function PlansPage() {
  const [filterStatus, setFilterStatus] = useState('')
  const [filterProjectId, setFilterProjectId] = useState('')
  const [limit] = useState(50)
  const [offset, setOffset] = useState(0)
  const [expandedId, setExpandedId] = useState<string | null>(null)

  const queryClient = useQueryClient()

  const { data: projects = [] } = useQuery({
    queryKey: ['projects'],
    queryFn: listProjects,
  })

  const { data, isLoading } = useQuery({
    queryKey: ['plans', filterProjectId, filterStatus, limit, offset],
    queryFn: () => listPlans({
      projectId: filterProjectId || undefined,
      status: filterStatus || undefined,
      limit,
      offset,
    }),
    refetchInterval: 10000,
  })

  const statusMutation = useMutation({
    mutationFn: ({ planId, status }: { planId: string; status: string }) =>
      updatePlanStatus(planId, status),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['plans'] }),
  })

  const plans = data?.plans || []
  const total = data?.total || 0
  const projectMap = new Map(projects.map((p: Project) => [p.id, p]))

  return (
    <div className="max-w-5xl mx-auto">
      <div className="mb-6">
        <h1 className="text-xl font-bold text-white">Plans</h1>
        <p className="text-sm text-gray-500 mt-1">Plans generated by Claude Code during chat sessions</p>
      </div>

      {/* Filters */}
      <div className="flex gap-3 mb-4">
        <select
          value={filterProjectId}
          onChange={e => { setFilterProjectId(e.target.value); setOffset(0) }}
          className="bg-gray-800 border border-gray-700 rounded px-3 py-1.5 text-sm text-gray-300"
        >
          <option value="">All Projects</option>
          {projects.map((p: Project) => (
            <option key={p.id} value={p.id}>{p.name} ({p.code})</option>
          ))}
        </select>
        <select
          value={filterStatus}
          onChange={e => { setFilterStatus(e.target.value); setOffset(0) }}
          className="bg-gray-800 border border-gray-700 rounded px-3 py-1.5 text-sm text-gray-300"
        >
          <option value="">All Statuses</option>
          {Object.entries(STATUS_STYLES).map(([key, { label }]) => (
            <option key={key} value={key}>{label}</option>
          ))}
        </select>
        <span className="text-xs text-gray-600 self-center ml-auto">
          {total} total plans
        </span>
      </div>

      {/* Plans list */}
      {isLoading ? (
        <div className="space-y-2">
          {[...Array(5)].map((_, i) => (
            <div key={i} className="h-16 animate-pulse rounded bg-gray-800/50" />
          ))}
        </div>
      ) : plans.length === 0 ? (
        <div className="text-center py-12 text-gray-500 text-sm">
          No plans captured yet. Plans will appear here when Claude Code enters plan mode during a chat session.
        </div>
      ) : (
        <div className="space-y-2">
          {plans.map((plan: Plan) => (
            <PlanRow
              key={plan.id}
              plan={plan}
              project={plan.projectCode ? projectMap.get(plan.projectCode) : undefined}
              expanded={expandedId === plan.id}
              onToggle={() => setExpandedId(expandedId === plan.id ? null : plan.id)}
              onStatusChange={(status) => statusMutation.mutate({ planId: plan.id, status })}
            />
          ))}
        </div>
      )}

      {/* Pagination */}
      {total > limit && (
        <div className="flex items-center justify-center gap-3 mt-4 pt-4 border-t border-gray-800">
          <button
            onClick={() => setOffset(Math.max(0, offset - limit))}
            disabled={offset === 0}
            className="text-xs text-gray-400 hover:text-white disabled:opacity-30 transition-colors"
          >
            Newer
          </button>
          <span className="text-xs text-gray-600">
            {offset + 1} - {Math.min(offset + limit, total)} of {total}
          </span>
          <button
            onClick={() => setOffset(offset + limit)}
            disabled={offset + limit >= total}
            className="text-xs text-gray-400 hover:text-white disabled:opacity-30 transition-colors"
          >
            Older
          </button>
        </div>
      )}
    </div>
  )
}

function PlanRow({ plan, project, expanded, onToggle, onStatusChange }: {
  plan: Plan
  project?: Project
  expanded: boolean
  onToggle: () => void
  onStatusChange: (status: string) => void
}) {
  const style = STATUS_STYLES[plan.status] || STATUS_STYLES.pending
  const snippet = plan.planText.length > 150 ? plan.planText.slice(0, 150) + '...' : plan.planText

  return (
    <div className={`rounded-lg border ${style.bg} overflow-hidden transition-all`}>
      {/* Header row */}
      <button
        onClick={onToggle}
        className="w-full flex items-start gap-3 px-3 py-2.5 text-left hover:bg-white/5 transition-colors"
      >
        <svg className={`w-4 h-4 mt-0.5 shrink-0 transition-transform ${expanded ? 'rotate-90' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
          <path strokeLinecap="round" strokeLinejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
        </svg>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className={`text-[10px] font-semibold uppercase tracking-wider ${style.color}`}>
              {style.label}
            </span>
            {project ? (
              <span className="text-[10px] bg-gray-700/50 text-gray-400 px-1.5 py-0.5 rounded font-mono">
                {project.name} ({project.code})
              </span>
            ) : (
              <span className="text-[10px] bg-gray-700/30 text-gray-600 px-1.5 py-0.5 rounded font-mono">
                No project
              </span>
            )}
            <span className="text-[10px] text-gray-600 ml-auto shrink-0">
              {formatTime(plan.createdAt)}
            </span>
          </div>
          {!expanded && (
            <p className="text-xs text-gray-400 mt-1 line-clamp-2 font-mono">{snippet}</p>
          )}
        </div>
      </button>

      {/* Expanded content */}
      {expanded && (
        <div className="border-t border-gray-700/40 px-4 py-3">
          <div className="prose prose-invert prose-sm max-w-none bg-gray-900/60 rounded p-3 mb-3 max-h-[60vh] overflow-y-auto">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{plan.planText}</ReactMarkdown>
          </div>

          {plan.feedback && (
            <div className="mb-3 rounded bg-orange-900/20 border border-orange-700/30 px-3 py-2">
              <span className="text-[10px] font-semibold text-orange-400 uppercase tracking-wider">Feedback</span>
              <p className="text-xs text-orange-200/80 mt-1">{plan.feedback}</p>
            </div>
          )}

          {plan.completedAt && (
            <p className="text-[10px] text-gray-500 mb-2">
              Completed: {formatTime(plan.completedAt)}
            </p>
          )}

          {/* Manual status actions */}
          <div className="flex gap-2 pt-1 border-t border-gray-700/30">
            {plan.status === 'accepted' && (
              <button
                onClick={() => onStatusChange('completed')}
                className="text-[10px] text-blue-400 hover:text-blue-300 transition-colors"
              >
                Mark Completed
              </button>
            )}
            {(plan.status === 'pending' || plan.status === 'accepted') && (
              <button
                onClick={() => onStatusChange('abandoned')}
                className="text-[10px] text-gray-500 hover:text-gray-400 transition-colors"
              >
                Mark Abandoned
              </button>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
